### PR TITLE
report queue state: messages, messages_ready, messages_unacknowledged

### PR DESCRIPTION
**Pull request by nordewal**
Report the following numbers per queue:

- total number of messages
- messages in ready state
- unacknowledged messages

### CODE REVIEW

**Comment by benhyland** [comment]
We're quite keen to see this go in, since we started using this plugin mainly because the documentation in the readme suggested that it provided messages_ready on a per-queue basis.

Is it possible to give us any idea how long it might take to get this merged and published to PyPI?

Also, I may be a bit confused, but why is the latest PyPI version at 1.4.0 while this repo is at 1.3.0? Is there another source for publication that I am missing?

Thanks very much for making this project :)

**Comment by jimbydamonk** [comment]
I am testing this now. Hope to be merged in soon. 
I didn't push some tags before so that explains the difference of 1.3.0 and 1.4.0.

**Comment by benhyland** [comment]
@jimbydamonk wow that was fast!
Thanks so much for the new release.
And thanks to @nordewal for the timely PR too :)

**Comment by jimbydamonk** [comment]
Thanks @nordewal  for the commit and @benhyland  for the reminder !

**Pull request merged**
